### PR TITLE
Adding 2018 and Run3 optics to Hector configuration

### PR DESCRIPTION
**Pull request by mundim**
Upload LHC optics file for 2018 and RunIII for HECTOR proton propagator (beamline simulator). They are needed to test nominal optics or PPS simulation with non-realistic optics. The files were tested for validity purpose only, they don't cause any trouble for the cmssw code.

### CODE REVIEW

**Comment by mundim** [comment]
Sorry to ask, but is there any problem with the PR? Have I done it properly? Thanks.

**Comment by smuzaffar** [comment]
@mundim , every thing good here. This Pr itself looks good but is there any cmssw pr where these new files are used?

**Comment by mundim** [comment]
Sorry to (kind of) put pressure on you... Yes, these are files for SimTransport/PPSProtonTransport to simulate nominal optics. It will be required when I ask to unhold (or create a new) PR  (cms-sw/cmssw#29916), where the proton transport is needed. The way PPSProtonTransport is right now, it uses conditions that are not yet in the Db for run3 (LHCInfo, for real optics), so the only way we have now for the simulation is to use nominal optics.

I could configure run3 to use optics from 2016 or 2017, but we prefer to have, even being nominal, to be the closest as possible to real conditions.

**Comment by smuzaffar** [comment]
we can start the tests with  cms-sw/cmssw#29916 once the conflicts on that PR are resolved

**Comment by smuzaffar** [comment]
+externals
these are all new files, so lets get them in IBs.

**Pull request merged**
